### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by peerchemist** [aallaire/oanda-candles#6]
Tried using this library but substituted EUR_USD with XAU_USD, this is the error.

> ValueError: Price out of reasonable range: 1783.223

**Comment by aallaire** [comment]
As stated in the Readme.md caveats, this package only supports the 28 pairs from the 8 major currencies. It doesn't have any precious metal support. The Price object it uses has some heuristic logic that depends on this, specifically a Price can be constructed without specifying a quote currency even though the Price object has methods that can convert to PIPs. Specifically it judges prices like 100.33 to be be in terms of Yen, and prices like 1.32233 to be in terms of one of the other currencies. The value 1783.223 is beyond the expected range of either so it threw an error. The Price class is defined in the forex-types package which has this github: https://github.com/aallaire/python_forex_types

**Comment by aallaire** [comment]
btw: I am not against having my forex-types and oanda-candles packages expanded to cover precious metals. But this is not a feature I anticipate adding myself anytime soon. But if someone wants to work on a github PR for it then I would be happy to review it and merge it if it seems good.
